### ISSUE TITLE
LETS GOOOO!!! i can finally do 1+1 😅

### ISSUE THREAD

**Issue by ghost** [chillzeus/simulation#3]

**Comment by chillzeus** [comment]
hmmmm? lol
also how'd you find my github? i didn't think i was getting that kind of web traffic :)

**Comment by ghost** [comment]
Cause of Temmie, aka 77z, he had it on his status for github lol, anyways nice to meet you :)

**Comment by chillzeus** [comment]
nice to meet you too! 77z is quite the programmer

**Comment by ghost** [comment]
yea xD

**Comment by ghost** [comment]
Do you have Discord?

**Comment by chillzeus** [comment]
yeah, ChillZeus#1360

**Comment by ghost** [comment]
Alright ty

**Comment by ghost** [comment]
I added you as XFaon#8699
